"""
Mundial26 — World Cup 2026 Forecast Dashboard
Run locally with:  streamlit run app.py
Loads the forecast produced by notebooks/04_simulation.ipynb (models/forecast.csv).
"""
import os
import pandas as pd
import streamlit as st
import plotly.express as px

st.set_page_config(page_title="Mundial26 — World Cup 2026 Forecast",
                   page_icon="⚽", layout="wide")

FORECAST_PATH = "models/forecast.csv"
TEAL = "#2a9d8f"


@st.cache_data
def load_forecast(path):
    df = pd.read_csv(path)
    return df.sort_values("Win %", ascending=False).reset_index(drop=True)


# ---- Header ----
st.title("⚽ Mundial26 — 2026 World Cup Forecast")
st.caption(
    "A Monte-Carlo forecast built on an ensemble of an Elo ratings model and a "
    "Dixon–Coles goals model, fit on 150+ years of international results. "
    "Odds update as real tournament results come in."
)

if not os.path.exists(FORECAST_PATH):
    st.error(
        f"Couldn't find `{FORECAST_PATH}`. Run `notebooks/04_simulation.ipynb` first "
        "to generate the forecast, then refresh this page."
    )
    st.stop()

df = load_forecast(FORECAST_PATH)

# ---- Favourites KPI row ----
st.subheader("Title favourites")
cols = st.columns(5)
for col, (_, row) in zip(cols, df.head(5).iterrows()):
    col.metric(row["Team"], f"{row['Win %']:.1f}%", help=f"Group {row['Group']}")

st.divider()

tab_odds, tab_groups, tab_team, tab_about = st.tabs(
    ["🏆 Title odds", "📋 Groups", "🔎 Team explorer", "ℹ️ How it works"]
)

# ---- Title odds ----
with tab_odds:
    n = st.slider("How many teams to show", 5, 30, 15)
    top = df.head(n)
    fig = px.bar(
        top.iloc[::-1], x="Win %", y="Team", orientation="h",
        text=top.iloc[::-1]["Win %"].map(lambda v: f"{v:.1f}%"),
        color_discrete_sequence=[TEAL],
        title=f"Probability of winning the 2026 World Cup (top {n})",
    )
    fig.update_layout(height=28 * n + 120, yaxis_title="", xaxis_title="Win probability (%)")
    st.plotly_chart(fig, use_container_width=True)

    st.dataframe(
        df[["Team", "Group", "Win %", "Final %", "Semi %", "Advance %"]],
        use_container_width=True, hide_index=True,
    )

# ---- Groups ----
with tab_groups:
    st.write("Each team's modelled chance of **advancing past the group stage**.")
    groups = sorted(df["Group"].unique())
    gcols = st.columns(3)
    for i, g in enumerate(groups):
        sub = df[df["Group"] == g].sort_values("Advance %", ascending=False)
        with gcols[i % 3]:
            st.markdown(f"**Group {g}**")
            for _, r in sub.iterrows():
                st.write(f"{r['Team']} — {r['Advance %']:.0f}%")
            st.write("")

# ---- Team explorer ----
with tab_team:
    team = st.selectbox("Pick a team", df["Team"].tolist())
    r = df[df["Team"] == team].iloc[0]
    st.markdown(f"### {team}  ·  Group {r['Group']}")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Advance from group", f"{r['Advance %']:.1f}%")
    c2.metric("Reach semi-final", f"{r['Semi %']:.1f}%")
    c3.metric("Reach final", f"{r['Final %']:.1f}%")
    c4.metric("Win the cup", f"{r['Win %']:.1f}%")

    stages = pd.DataFrame({
        "Stage": ["Advance", "Semi-final", "Final", "Champion"],
        "Probability": [r["Advance %"], r["Semi %"], r["Final %"], r["Win %"]],
    })
    fig = px.bar(stages, x="Stage", y="Probability", color_discrete_sequence=[TEAL],
                 text=stages["Probability"].map(lambda v: f"{v:.1f}%"))
    fig.update_layout(yaxis_title="Probability (%)", xaxis_title="")
    st.plotly_chart(fig, use_container_width=True)

# ---- About ----
with tab_about:
    st.markdown(
        """
**How the forecast works**

1. **Data** — every international match since 1872 (~49,000 games).
2. **Two models** — an **Elo** ratings model that tracks team strength over time, and a
   **Dixon–Coles** model that predicts goals scored and so handles draws naturally.
3. **Ensemble** — the two are blended (60/40); in backtests the blend beats either alone.
4. **Simulation** — the tournament is played out 10,000 times with the real group draw and
   the results so far locked in, then the remaining matches simulated to a champion.
5. **Validated** — backtested on the 2018 and 2022 World Cups, beating naive baselines on
   log loss and Brier score, with both eventual champions rated near the top beforehand.

Built by **Mahmoud Ahmed** ·
[GitHub](https://github.com/mmahmoudahmedd/mundial26) ·
[LinkedIn](https://linkedin.com/in/mahmoud-ahmed-9454a8253)
        """
    )

st.divider()
st.caption("Mundial26 · forecast regenerated by re-running the simulation notebook on fresh data.")
